version: 2.0
jobs:
  build:
    resource_class: medium
    docker:
      - image: circleci/node:11.9.0
    steps:
      - checkout
      - run:
          name: "Install ng CLI"
          command: (echo y; echo y; echo y; echo y;) | sudo npm install -g @angular/cli
      - run:
          name: Check current version of node
          command: node -v
      - run:
          name: Install npm dependencies
          command: npm install
      - run:
          name: Build the project
          command: (echo y; echo y; ) | ng build --prod --aot
      - run:
          name: woot
          command: echo woot
      - add_ssh_keys:
          fingerprints:
            - "3f:c4:94:50:69:a6:1d:f6:de:98:4e:17:64:e9:57:24"
      - run:
          name: Deploy front
          command: scp -P $SSH_PORT -r dist/cfptime-frontend/* $SSH_USERNAME@$CFPTIME_SERVER:$CFPTIME_PATH